### ISSUE TITLE
CSS animation instead of animated gif

### ISSUE THREAD

**Issue by corydavidwilliam** [wataruoguchi/clever-infinite-scroll#1]
Great plugin! What would be the best way to add a CSS animation while loading instead of the animated gif that comes with the plugin?

**Comment by wataruoguchi** [comment]
For now, if I want to do it I would use #cis-load-img (This is the gif image's id)
Here is my idea..
Step 1. Hide the image by jQuery/CSS
Step 2. Add whatever by CSS

**Comment by corydavidwilliam** [comment]
Thanks for this.  I'll give it a shot!
