### ISSUE TITLE
Preload trigger offset

### ISSUE THREAD

**Issue by corydavidwilliam** [wataruoguchi/clever-infinite-scroll#2]
Is there an option to set the offset distance for fetching the next page?

**Comment by wataruoguchi** [comment]
No option for it, though you can set it changing "threshold" variable on line 64.
It's good idea to implement, I'll take the idea.

**Comment by corydavidwilliam** [comment]
Thanks for this.  Much appreciated.

**Comment by wataruoguchi** [comment]
Add offset option
