### ISSUE TITLE
Indicate active content

### ISSUE THREAD

**Issue by corydavidwilliam** [wataruoguchi/clever-infinite-scroll#3]
Is it possible to add an "active" class to the contentSelector which is currently in view?

I imagine something tied to the changeTitleAndURL function?

**Comment by corydavidwilliam** [comment]
Right now I am adding this to the if statement within changeTitleAndURL:

``` javascript
if($("title").text() !== title) {
  // If it has changed
  // Remove class on all contentSelectors
  $(settings.contentSelector).removeClass("active");
  // Add class on active contentSelector
  $(_value).addClass("active");
  setTitleAndHistory(title, path);
}
```

Not sure if there is a better way to do this.

**Comment by wataruoguchi** [comment]
I think it is the best way for that. I will implement it hopefully within a week.

**Comment by wataruoguchi** [comment]
Add the feature. Thanks!
