### ISSUE TITLE
Multiple items with "active" class

### ISSUE THREAD

**Issue by corydavidwilliam** [wataruoguchi/clever-infinite-scroll#4]
I've applied your latest update that includes adding the "active" class within changeTitleAndURL.

However, I am currently experiencing an issue where if the offset loads the next item without scrolling to it, both the viewable item and the next item have the "active" class...

**Comment by wataruoguchi** [comment]
Hi @corydavidwilliam , thank you for reporting. Let me take a look someday soon!

**Comment by wataruoguchi** [comment]
@corydavidwilliam,
`$(settings.contentSelector).removeClass("active");` removes all `.active`, so it shouldn't happen. Could you give me more inputs please?

**Comment by corydavidwilliam** [comment]
No problem. Please view this screencast.  Let me know if you need any additional details.

https://www.dropbox.com/s/g2yjc7vn7l2pwro/CleverScroll.mp4?dl=0

**Comment by wataruoguchi** [comment]
It seems like it loads the js again?
Can you try using this? I made the branch for this issue.
[branch(preventMultipleActive)](https://github.com/wataruoguchi/clever-infinite-scroll/tree/preventMultipleActive)

**Comment by corydavidwilliam** [comment]
I apologize, this is my error.  The contentSelector that is loaded had the "active" class on it already.  I removed this and am now adding that class to the initial contentSelector via jQuery onReady.

**Comment by wataruoguchi** [comment]
Oh alright. Nice website btw.
