### ISSUE TITLE
Breaks with Overflow:Auto on Html, Body

### ISSUE THREAD

**Issue by toobulo** [wataruoguchi/clever-infinite-scroll#5]
Great plugin, seems on par with Infinite Ajax Scroll.  However, both run into the same issue if you use the following CSS:

```
html, body {
    height: 100%;
    width: 100%;
    overflow: auto;
}
```

This prevents the JS from loading anything.

**Comment by wataruoguchi** [comment]
Hi,
Thank you for seeing the plugin.
Have you ever tried with `overflow: scroll;` or `visible` instead of `auto`?
Also I would like to know the reason why you stick on using `auto`.
Happy coding!

**Comment by toobulo** [comment]
The reason for using `overflow:auto` is due to an issue in iOS Safari 9+ for iPhone.  See here: http://stackoverflow.com/questions/35333654/fixed-elements-arent-clickable-when-i-quickly-scroll-to-the-bottom-in-ios-safar 

`overflow: scroll;` also appears to break the Infinite Scroll.

**Comment by wataruoguchi** [comment]
It seems my plugin works with `overflow: scroll;`. Could you tell me what browser(s) & user agent you've tried and on what ones my plugin doesn't work with `overflow: scroll;`?
